version: '3'

services:
  app:
    image: fastblog:latest
    restart: always
    ports:
      - "8005:80"
    env_file:
            - .env_example
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    restart: always

    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000


  redis:
      image: redis:alpine
      restart: always
      expose:
          - 12534

      stop_grace_period: 3m
      healthcheck:
          test: [ "CMD", "redis-cli", "ping" ]
          interval: 1s
          timeout: 3s
          retries: 30
      ports:
          - '6378:6379'


  celery_worker:
    image: celery:latest
    command: ['celery',  'worker','-A', 'fast_bloge.main.celery' ,'-l','info']
    environment:
          - CELERY_BROKER_URL=redis://redis:6379/0
          - CELERY_RESULT_BACKEND=redis://redis:6379/0

    env_file:
      - .env_example
    depends_on:
      - redis
      - db

